OPENQASM 2.0;
include "qelib1.inc";
qreg qubits[5];

h qubits[4];
x qubits[0];
x qubits[1];
x qubits[2];
ccx qubits[0], qubits[1], qubits[3];
ccx qubits[3], qubits[2], qubits[4];
ccx qubits[0], qubits[1], qubits[3];
x qubits[0];
x qubits[1];
x qubits[2];
h qubits[0];
h qubits[1];
h qubits[2];
x qubits[0];
x qubits[1];
x qubits[2];
ccx qubits[0], qubits[1], qubits[3];
cz qubits[3], qubits[2];
ccx qubits[0], qubits[1], qubits[3];
x qubits[0];
x qubits[1];
x qubits[2];
h qubits[0];
h qubits[1];
h qubits[2];
h qubits[4];
