name: C/C++ CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-debug-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install libboost-filesystem-dev libboost-test-dev libboost-regex-dev
    - run: make debug
    - run: cp /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.* build/unit_tests/
    - run: cp /usr/lib/x86_64-linux-gnu/libboost_regex.so.*               build/unit_tests/
    - run: cp libz3.so.*                                                  build/unit_tests/
    - uses: actions/upload-artifact@v4.3.5
      with:
        name: AutoQ-debug-ubuntu
        path: |
          Makefile
          build/
          unit_tests/
          benchmarks/all/

  test-debug-ubuntu:
    needs: build-debug-ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: AutoQ-debug-ubuntu
    # - run: pwd
    # - run: ls -a
    - run: cd build/unit_tests/ && chmod +x ./explicit_tree_aut_test && LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./explicit_tree_aut_test

  build-release-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install libboost-filesystem-dev libboost-test-dev libboost-regex-dev
    - run: make release
    - run: cp /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.* build/unit_tests/
    - run: cp /usr/lib/x86_64-linux-gnu/libboost_regex.so.*               build/unit_tests/
    - run: cp libz3.so.*                                                  build/unit_tests/
    - uses: actions/upload-artifact@v4.3.5
      with:
        name: AutoQ-release-ubuntu
        path: |
          Makefile
          build/
          unit_tests/
          benchmarks/all/

  test-release-ubuntu:
    needs: build-release-ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: AutoQ-release-ubuntu
    # - run: pwd
    # - run: ls -a
    - run: cd build/unit_tests/ && chmod +x ./explicit_tree_aut_test && LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./explicit_tree_aut_test

  build-debug-wsl:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/setup-wsl2@main
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y libboost-filesystem-dev libboost-test-dev libboost-regex-dev git make gcc g++ cmake
          make debug
          cp /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.* build/unit_tests/
          cp /usr/lib/x86_64-linux-gnu/libboost_regex.so.*               build/unit_tests/
          cp libz3.so.*                                                  build/unit_tests/
        shell: wsl-run {0} # add this to run the commands inside linux
      - run: |
          wsl -d Ubuntu -e bash -c "tar -czf autoq-debug-wsl.tar.gz Makefile build/ unit_tests/ benchmarks/all/"
      - uses: actions/upload-artifact@v4.3.5
        with:
          name: AutoQ-debug-wsl
          path: autoq-debug-wsl.tar.gz

  test-debug-wsl:
    needs: build-debug-wsl
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/setup-wsl2@main
      - uses: actions/download-artifact@v4
        with:
          name: AutoQ-debug-wsl
      - run: |
          tar -xzf autoq-debug-wsl.tar.gz 
          cd build/unit_tests/ && chmod +x ./explicit_tree_aut_test && LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./explicit_tree_aut_test
        shell: wsl-run {0} # add this to run the commands inside linux

  build-release-wsl:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/setup-wsl2@main
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y libboost-filesystem-dev libboost-test-dev libboost-regex-dev git make gcc g++ cmake
          make release
          cp /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.* build/unit_tests/
          cp /usr/lib/x86_64-linux-gnu/libboost_regex.so.*               build/unit_tests/
          cp libz3.so.*                                                  build/unit_tests/
        shell: wsl-run {0} # add this to run the commands inside linux
      - run: |
          wsl -d Ubuntu -e bash -c "tar -czf /tmp/autoq-release-wsl.tar.gz Makefile build/ unit_tests/ benchmarks/all/"
      - uses: actions/upload-artifact@v4.3.5
        with:
          name: AutoQ-release-wsl
          path: /tmp/autoq-release-wsl.tar.gz

  test-release-wsl:
    needs: build-release-wsl
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/setup-wsl2@main
      - uses: actions/download-artifact@v4
        with:
          name: AutoQ-release-wsl
      - run: |
          tar -xzf autoq-release-wsl.tar.gz
          cd build/unit_tests/ && chmod +x ./explicit_tree_aut_test && LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./explicit_tree_aut_test
        shell: wsl-run {0} # add this to run the commands inside linux

  build-debug-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - run: brew install gcc make cmake boost
    - run: make debug
    - run: cp /opt/homebrew/lib/libboost_unit_test_framework.dylib build/unit_tests/
    - run: cp /opt/homebrew/lib/libboost_filesystem.dylib          build/unit_tests/
    - run: cp /opt/homebrew/lib/libboost_system.dylib              build/unit_tests/
    - run: cp /opt/homebrew/lib/libboost_regex.dylib               build/unit_tests/
    - run: cp /opt/homebrew/lib/libboost_atomic.dylib              build/unit_tests/
    # # - run: cp /home/runner/work/AutoQ/AutoQ/AutoQ/libz3.so.* /Users/runner/work/AutoQ/AutoQ/AutoQ/build/unit_tests/
    - uses: actions/upload-artifact@v4.3.5
      with:
        name: AutoQ-debug-macos

        path: |
          Makefile
          build/
          unit_tests/
          benchmarks/all/

  test-debug-macos:
    needs: build-debug-macos
    runs-on: macos-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: AutoQ-debug-macos
    # - run: pwd
    # - run: ls -a
    - run: cd build/unit_tests/ && chmod +x ./explicit_tree_aut_test && DYLD_LIBRARY_PATH=.:$DYLD_LIBRARY_PATH ./explicit_tree_aut_test

  build-release-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - run: brew install gcc make cmake boost
    - run: make release
    - run: cp /opt/homebrew/lib/libboost_unit_test_framework.dylib build/unit_tests/
    - run: cp /opt/homebrew/lib/libboost_filesystem.dylib          build/unit_tests/
    - run: cp /opt/homebrew/lib/libboost_system.dylib              build/unit_tests/
    - run: cp /opt/homebrew/lib/libboost_regex.dylib               build/unit_tests/
    - run: cp /opt/homebrew/lib/libboost_atomic.dylib              build/unit_tests/
    # # - run: cp /home/runner/work/AutoQ/AutoQ/AutoQ/libz3.so.* /Users/runner/work/AutoQ/AutoQ/AutoQ/build/unit_tests/
    - uses: actions/upload-artifact@v4.3.5
      with:
        name: AutoQ-release-macos
        path: |
          Makefile
          build/
          unit_tests/
          benchmarks/all/

  test-release-macos:
    needs: build-release-macos
    runs-on: macos-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: AutoQ-release-macos
    # - run: pwd
    # - run: ls -a
    - run: cd build/unit_tests/ && chmod +x ./explicit_tree_aut_test && DYLD_LIBRARY_PATH=.:$DYLD_LIBRARY_PATH ./explicit_tree_aut_test
