name: C/C++ CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-debug-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install libboost-filesystem-dev libboost-test-dev libboost-regex-dev
    - run: git clone https://github.com/alan23273850/AutoQ.git
    - run: cd AutoQ && git checkout ${{ github.ref_name }} && mkdir build && make debug
    - run: cp /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.74.0 /home/runner/work/AutoQ/AutoQ/AutoQ/build/unit_tests/
    - run: cp /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.74.0 /home/runner/work/AutoQ/AutoQ/AutoQ/build/unit_tests/
    - run: cp /home/runner/work/AutoQ/AutoQ/AutoQ/libz3.so.4.12 /home/runner/work/AutoQ/AutoQ/AutoQ/build/unit_tests/
    - uses: actions/upload-artifact@v4.3.5
      with:
        name: AutoQ-debug-ubuntu
        path: |
          AutoQ/Makefile
          AutoQ/build/
          AutoQ/unit_tests/
          AutoQ/benchmarks/all/
  test-debug-ubuntu:
    needs: build-debug-ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: AutoQ-debug-ubuntu
        path: AutoQ/
    # - run: pwd
    # - run: ls -a
    - run: cd AutoQ/build/unit_tests/ && chmod +x ./explicit_tree_aut_test && LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./explicit_tree_aut_test
  build-release-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install libboost-filesystem-dev libboost-test-dev libboost-regex-dev
    - run: git clone https://github.com/alan23273850/AutoQ.git
    - run: cd AutoQ && git checkout ${{ github.ref_name }} && mkdir build && make release
    - run: cp /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.74.0 /home/runner/work/AutoQ/AutoQ/AutoQ/build/unit_tests/
    - run: cp /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.74.0 /home/runner/work/AutoQ/AutoQ/AutoQ/build/unit_tests/
    - run: cp /home/runner/work/AutoQ/AutoQ/AutoQ/libz3.so.4.12 /home/runner/work/AutoQ/AutoQ/AutoQ/build/unit_tests/
    - uses: actions/upload-artifact@v4.3.5
      with:
        name: AutoQ-release-ubuntu
        path: |
          AutoQ/Makefile
          AutoQ/build/
          AutoQ/unit_tests/
          AutoQ/benchmarks/all/
  test-release-ubuntu:
    needs: build-release-ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: AutoQ-release-ubuntu
        path: AutoQ/
    # - run: pwd
    # - run: ls -a
    - run: cd AutoQ/build/unit_tests/ && chmod +x ./explicit_tree_aut_test && LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./explicit_tree_aut_test
  build-debug-macos:
    runs-on: macos-latest
    steps:
    - run: brew install gcc make cmake boost
    - run: git clone https://github.com/alan23273850/AutoQ.git
    - run: cd AutoQ && git checkout ${{ github.ref_name }} && mkdir build && make debug
    - run: cp /opt/homebrew/lib/libboost_unit_test_framework.dylib /Users/runner/work/AutoQ/AutoQ/AutoQ/build/unit_tests/
    - run: cp /opt/homebrew/lib/libboost_filesystem.dylib /Users/runner/work/AutoQ/AutoQ/AutoQ/build/unit_tests/
    - run: cp /opt/homebrew/lib/libboost_system.dylib /Users/runner/work/AutoQ/AutoQ/AutoQ/build/unit_tests/
    - run: cp /opt/homebrew/lib/libboost_regex.dylib /Users/runner/work/AutoQ/AutoQ/AutoQ/build/unit_tests/
    # # - run: cp /home/runner/work/AutoQ/AutoQ/AutoQ/libz3.so.4.12 /Users/runner/work/AutoQ/AutoQ/AutoQ/build/unit_tests/
    - uses: actions/upload-artifact@v4.3.5
      with:
        name: AutoQ-debug-macos
        path: |
          AutoQ/Makefile
          AutoQ/build/
          AutoQ/unit_tests/
          AutoQ/benchmarks/all/
  test-debug-macos:
    needs: build-debug-macos
    runs-on: macos-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: AutoQ-debug-macos
        path: AutoQ/
    # - run: pwd
    # - run: ls -a
    - run: cd AutoQ/build/unit_tests/ && chmod +x ./explicit_tree_aut_test && DYLD_LIBRARY_PATH=.:$DYLD_LIBRARY_PATH ./explicit_tree_aut_test
  build-release-macos:
    runs-on: macos-latest
    steps:
    - run: brew install gcc make cmake boost
    - run: git clone https://github.com/alan23273850/AutoQ.git
    - run: cd AutoQ && git checkout ${{ github.ref_name }} && mkdir build && make release
    - run: cp /opt/homebrew/lib/libboost_unit_test_framework.dylib /Users/runner/work/AutoQ/AutoQ/AutoQ/build/unit_tests/
    - run: cp /opt/homebrew/lib/libboost_filesystem.dylib /Users/runner/work/AutoQ/AutoQ/AutoQ/build/unit_tests/
    - run: cp /opt/homebrew/lib/libboost_system.dylib /Users/runner/work/AutoQ/AutoQ/AutoQ/build/unit_tests/
    - run: cp /opt/homebrew/lib/libboost_regex.dylib /Users/runner/work/AutoQ/AutoQ/AutoQ/build/unit_tests/
    # # - run: cp /home/runner/work/AutoQ/AutoQ/AutoQ/libz3.so.4.12 /Users/runner/work/AutoQ/AutoQ/AutoQ/build/unit_tests/
    - uses: actions/upload-artifact@v4.3.5
      with:
        name: AutoQ-release-macos
        path: |
          AutoQ/Makefile
          AutoQ/build/
          AutoQ/unit_tests/
          AutoQ/benchmarks/all/
  test-release-macos:
    needs: build-release-macos
    runs-on: macos-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: AutoQ-release-macos
        path: AutoQ/
    # - run: pwd
    # - run: ls -a
    - run: cd AutoQ/build/unit_tests/ && chmod +x ./explicit_tree_aut_test && DYLD_LIBRARY_PATH=.:$DYLD_LIBRARY_PATH ./explicit_tree_aut_test